DECLARE
V_COUNT INTEGER;
BEGIN
SELECT COUNT(TABLE_NAME) INTO V_COUNT from USER_TABLES where TABLE_NAME = '__EFMigrationsHistory';
IF V_COUNT = 0 THEN
Begin
BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"__EFMigrationsHistory" (
    "MigrationId" NVARCHAR2(150) NOT NULL,
    "ProductVersion" NVARCHAR2(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
)';
END;

End;

END IF;
EXCEPTION
WHEN OTHERS THEN
    IF(SQLCODE != -942)THEN
        RAISE;
    END IF;
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"AcademicYears" (
    "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "Name" NVARCHAR2(20) NOT NULL,
    "StartDate" TIMESTAMP(7) NOT NULL,
    "EndDate" TIMESTAMP(7) NOT NULL,
    CONSTRAINT "PK_AcademicYears" PRIMARY KEY ("Id")
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"Buildings" (
    "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "Name" NVARCHAR2(100) NOT NULL,
    "Address" NVARCHAR2(200) NOT NULL,
    CONSTRAINT "PK_Buildings" PRIMARY KEY ("Id")
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"ClassTypes" (
    "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "Name" NVARCHAR2(100) NOT NULL,
    "Abbreviation" NVARCHAR2(10) NOT NULL,
    CONSTRAINT "PK_ClassTypes" PRIMARY KEY ("Id")
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"Faculties" (
    "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "Name" NVARCHAR2(100) NOT NULL,
    "Abbreviation" NVARCHAR2(10) NOT NULL,
    CONSTRAINT "PK_Departments" PRIMARY KEY ("Id")
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"Permissions" (
    "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "PermissionCode" NVARCHAR2(100) NOT NULL,
    "Description" NVARCHAR2(2000) NOT NULL,
    CONSTRAINT "PK_Permissions" PRIMARY KEY ("Id")
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"Roles" (
    "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "Name" NVARCHAR2(50) NOT NULL,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"Students" (
    "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "StudentID" NVARCHAR2(20) NOT NULL,
    "FirstName" NVARCHAR2(100) NOT NULL,
    "LastName" NVARCHAR2(100) NOT NULL,
    CONSTRAINT "PK_Students" PRIMARY KEY ("Id")
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"Subjects" (
    "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "Name" NVARCHAR2(200) NOT NULL,
    "Abbreviation" NVARCHAR2(20) NOT NULL,
    "Code" NVARCHAR2(50) NOT NULL,
    CONSTRAINT "PK_Subjects" PRIMARY KEY ("Id")
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"Teachers" (
    "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "AcademicTitle" NVARCHAR2(50) NOT NULL,
    "FirstName" NVARCHAR2(100) NOT NULL,
    "LastName" NVARCHAR2(100) NOT NULL,
    "Email" NVARCHAR2(100),
    CONSTRAINT "PK_Teachers" PRIMARY KEY ("Id")
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"Semesters" (
    "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "AcademicYearId" NUMBER(10) NOT NULL,
    "Name" NVARCHAR2(20) NOT NULL,
    "StartDate" TIMESTAMP(7) NOT NULL,
    "EndDate" TIMESTAMP(7) NOT NULL,
    CONSTRAINT "PK_Semesters" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Semesters_AcademicYears_AcademicYearId" FOREIGN KEY ("AcademicYearId") REFERENCES "AcademicYears" ("Id") ON DELETE CASCADE
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"Rooms" (
    "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "BuildingId" NUMBER(10) NOT NULL,
    "Number" NVARCHAR2(20) NOT NULL,
    "Capacity" NUMBER(10),
    "Type" NVARCHAR2(50) NOT NULL,
    CONSTRAINT "PK_Rooms" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Rooms_Buildings_BuildingId" FOREIGN KEY ("BuildingId") REFERENCES "Buildings" ("Id") ON DELETE CASCADE
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"FieldsOfStudy" (
    "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "DepartmentId" NUMBER(10) NOT NULL,
    "Name" NVARCHAR2(100) NOT NULL,
    "Degree" NVARCHAR2(50) NOT NULL,
    "Mode" NVARCHAR2(50) NOT NULL,
    CONSTRAINT "PK_FieldsOfStudy" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_FieldsOfStudy_Departments_DepartmentId" FOREIGN KEY ("DepartmentId") REFERENCES "Faculties" ("Id") ON DELETE CASCADE
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"RolePermissions" (
    "RoleId" NUMBER(10) NOT NULL,
    "PermissionId" NUMBER(10) NOT NULL,
    CONSTRAINT "PK_RolePermissions" PRIMARY KEY ("RoleId", "PermissionId"),
    CONSTRAINT "FK_RolePermissions_Permissions_PermissionId" FOREIGN KEY ("PermissionId") REFERENCES "Permissions" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_RolePermissions_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"Users" (
    "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "Username" NVARCHAR2(50) NOT NULL,
    "PasswordHash" NVARCHAR2(255) NOT NULL,
    "Email" NVARCHAR2(100) NOT NULL,
    "RoleId" NUMBER(10) NOT NULL,
    "StudentId" NUMBER(10),
    "TeacherId" NUMBER(10),
    "IsActive" BOOLEAN NOT NULL,
    "LastLogin" TIMESTAMP(7),
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Users_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Users_Students_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Students" ("Id"),
    CONSTRAINT "FK_Users_Teachers_TeacherId" FOREIGN KEY ("TeacherId") REFERENCES "Teachers" ("Id")
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"Specializations" (
    "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "FieldOfStudyId" NUMBER(10) NOT NULL,
    "Name" NVARCHAR2(100) NOT NULL,
    CONSTRAINT "PK_Specializations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Specializations_FieldsOfStudy_FieldOfStudyId" FOREIGN KEY ("FieldOfStudyId") REFERENCES "FieldsOfStudy" ("Id") ON DELETE CASCADE
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"Groups" (
    "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "SemesterId" NUMBER(10) NOT NULL,
    "SpecializationId" NUMBER(10) NOT NULL,
    "ClassTypeId" NUMBER(10) NOT NULL,
    "Name" NVARCHAR2(50) NOT NULL,
    CONSTRAINT "PK_Groups" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Groups_ClassTypes_ClassTypeId" FOREIGN KEY ("ClassTypeId") REFERENCES "ClassTypes" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Groups_Semesters_SemesterId" FOREIGN KEY ("SemesterId") REFERENCES "Semesters" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Groups_Specializations_SpecializationId" FOREIGN KEY ("SpecializationId") REFERENCES "Specializations" ("Id") ON DELETE CASCADE
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"StudentGroups" (
    "StudentId" NUMBER(10) NOT NULL,
    "GroupId" NUMBER(10) NOT NULL,
    CONSTRAINT "PK_StudentGroups" PRIMARY KEY ("StudentId", "GroupId"),
    CONSTRAINT "FK_StudentGroups_Groups_GroupId" FOREIGN KEY ("GroupId") REFERENCES "Groups" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_StudentGroups_Students_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Students" ("Id") ON DELETE CASCADE
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"Timetables" (
    "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "SubjectId" NUMBER(10) NOT NULL,
    "TeacherId" NUMBER(10) NOT NULL,
    "RoomId" NUMBER(10) NOT NULL,
    "GroupId" NUMBER(10) NOT NULL,
    "ClassTypeId" NUMBER(10) NOT NULL,
    "DayOfWeek" NUMBER(10) NOT NULL,
    "StartTime" INTERVAL DAY(8) TO SECOND(7) NOT NULL,
    "EndTime" INTERVAL DAY(8) TO SECOND(7) NOT NULL,
    "WeekCycle" NVARCHAR2(20) NOT NULL,
    CONSTRAINT "PK_Timetables" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Timetables_ClassTypes_ClassTypeId" FOREIGN KEY ("ClassTypeId") REFERENCES "ClassTypes" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Timetables_Groups_GroupId" FOREIGN KEY ("GroupId") REFERENCES "Groups" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Timetables_Rooms_RoomId" FOREIGN KEY ("RoomId") REFERENCES "Rooms" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Timetables_Subjects_SubjectId" FOREIGN KEY ("SubjectId") REFERENCES "Subjects" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Timetables_Teachers_TeacherId" FOREIGN KEY ("TeacherId") REFERENCES "Teachers" ("Id") ON DELETE CASCADE
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"ScheduleChanges" (
    "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "TimetableId" NUMBER(10) NOT NULL,
    "ChangeDate" TIMESTAMP(7) NOT NULL,
    "ChangeType" NVARCHAR2(50) NOT NULL,
    "NewRoomId" NUMBER(10),
    "NewTeacherId" NUMBER(10),
    "NewStartTime" INTERVAL DAY(8) TO SECOND(7),
    "NewEndTime" INTERVAL DAY(8) TO SECOND(7),
    CONSTRAINT "PK_ScheduleChanges" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ScheduleChanges_Rooms_NewRoomId" FOREIGN KEY ("NewRoomId") REFERENCES "Rooms" ("Id"),
    CONSTRAINT "FK_ScheduleChanges_Teachers_NewTeacherId" FOREIGN KEY ("NewTeacherId") REFERENCES "Teachers" ("Id"),
    CONSTRAINT "FK_ScheduleChanges_Timetables_TimetableId" FOREIGN KEY ("TimetableId") REFERENCES "Timetables" ("Id") ON DELETE CASCADE
)';
END;
/

CREATE INDEX "IX_FieldsOfStudy_DepartmentId" ON "FieldsOfStudy" ("DepartmentId")
/

CREATE INDEX "IX_Groups_ClassTypeId" ON "Groups" ("ClassTypeId")
/

CREATE INDEX "IX_Groups_SemesterId" ON "Groups" ("SemesterId")
/

CREATE INDEX "IX_Groups_SpecializationId" ON "Groups" ("SpecializationId")
/

CREATE INDEX "IX_RolePermissions_PermissionId" ON "RolePermissions" ("PermissionId")
/

CREATE INDEX "IX_Rooms_BuildingId" ON "Rooms" ("BuildingId")
/

CREATE INDEX "IX_ScheduleChanges_NewRoomId" ON "ScheduleChanges" ("NewRoomId")
/

CREATE INDEX "IX_ScheduleChanges_NewTeacherId" ON "ScheduleChanges" ("NewTeacherId")
/

CREATE INDEX "IX_ScheduleChanges_TimetableId" ON "ScheduleChanges" ("TimetableId")
/

CREATE INDEX "IX_Semesters_AcademicYearId" ON "Semesters" ("AcademicYearId")
/

CREATE INDEX "IX_Specializations_FieldOfStudyId" ON "Specializations" ("FieldOfStudyId")
/

CREATE INDEX "IX_StudentGroups_GroupId" ON "StudentGroups" ("GroupId")
/

CREATE INDEX "IX_Timetables_ClassTypeId" ON "Timetables" ("ClassTypeId")
/

CREATE INDEX "IX_Timetables_GroupId" ON "Timetables" ("GroupId")
/

CREATE INDEX "IX_Timetables_RoomId" ON "Timetables" ("RoomId")
/

CREATE INDEX "IX_Timetables_SubjectId" ON "Timetables" ("SubjectId")
/

CREATE INDEX "IX_Timetables_TeacherId" ON "Timetables" ("TeacherId")
/

CREATE INDEX "IX_Users_RoleId" ON "Users" ("RoleId")
/

CREATE INDEX "IX_Users_StudentId" ON "Users" ("StudentId")
/

CREATE INDEX "IX_Users_TeacherId" ON "Users" ("TeacherId")
/

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES (N'20260501121545_InitialOracleSetup', N'10.0.7')
/

declare
   l_nullable user_tab_columns.nullable % type;
begin 
   select nullable into l_nullable 
   from user_tab_columns 
  where table_name = 'Timetables' 
  and column_name = 'WeekCycle' 
;
   if l_nullable = 'N' then 
        EXECUTE IMMEDIATE 'ALTER TABLE "Timetables" MODIFY "WeekCycle" NUMBER(10) ';
 else 
        EXECUTE IMMEDIATE 'ALTER TABLE "Timetables" MODIFY "WeekCycle" NUMBER(10) NOT NULL';
 end if;
end;
/

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES (N'20260501135208_EnumWeekCycle', N'10.0.7')
/

ALTER TABLE "FieldsOfStudy" DROP CONSTRAINT "FK_FieldsOfStudy_Departments_DepartmentId"
/

DROP TABLE "Departments"
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"Faculties" (
    "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "Name" NVARCHAR2(100) NOT NULL,
    "Abbreviation" NVARCHAR2(10) NOT NULL,
    CONSTRAINT "PK_Faculties" PRIMARY KEY ("Id")
)';
END;
/

ALTER TABLE "FieldsOfStudy" ADD CONSTRAINT "FK_FieldsOfStudy_Faculties_DepartmentId" FOREIGN KEY ("DepartmentId") REFERENCES "Faculties" ("Id") ON DELETE CASCADE
/

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES (N'20260501154142_ChangeNameToFaculty', N'10.0.7')
/

ALTER TABLE "FieldsOfStudy" DROP CONSTRAINT "FK_FieldsOfStudy_Faculties_DepartmentId"
/

ALTER TABLE "FieldsOfStudy" RENAME COLUMN "DepartmentId" TO "FacultyId"
/

ALTER INDEX "IX_FieldsOfStudy_DepartmentId" RENAME TO "IX_FieldsOfStudy_FacultyId"
/

ALTER TABLE "Buildings" ADD "FacultyId" NUMBER(10) DEFAULT 0 NOT NULL
/

CREATE INDEX "IX_Buildings_FacultyId" ON "Buildings" ("FacultyId")
/

ALTER TABLE "Buildings" ADD CONSTRAINT "FK_Buildings_Faculties_FacultyId" FOREIGN KEY ("FacultyId") REFERENCES "Faculties" ("Id") ON DELETE CASCADE
/

ALTER TABLE "FieldsOfStudy" ADD CONSTRAINT "FK_FieldsOfStudy_Faculties_FacultyId" FOREIGN KEY ("FacultyId") REFERENCES "Faculties" ("Id") ON DELETE CASCADE
/

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES (N'20260501154752_RepairFacultyConnections', N'10.0.7')
/

ALTER TABLE "Groups" DROP CONSTRAINT "FK_Groups_ClassTypes_ClassTypeId"
/

ALTER TABLE "Timetables" DROP CONSTRAINT "FK_Timetables_ClassTypes_ClassTypeId"
/

DROP TABLE "ClassTypes"
/

DROP INDEX "IX_Timetables_ClassTypeId"
/

DROP INDEX "IX_Groups_ClassTypeId"
/

ALTER TABLE "Timetables" DROP COLUMN "ClassTypeId"
/

ALTER TABLE "Groups" DROP COLUMN "ClassTypeId"
/

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES (N'20260501160614_RemoveClassType', N'10.0.7')
/

ALTER TABLE "Timetables" ADD "ClassType" NUMBER(10) DEFAULT 0 NOT NULL
/

ALTER TABLE "Groups" ADD "ClassType" NUMBER(10) DEFAULT 0 NOT NULL
/

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES (N'20260501161246_EnumClassType', N'10.0.7')
/

ALTER TABLE "Groups" DROP CONSTRAINT "FK_Groups_Specializations_SpecializationId"
/

declare
   l_nullable user_tab_columns.nullable % type;
begin 
   select nullable into l_nullable 
   from user_tab_columns 
  where table_name = 'Groups' 
  and column_name = 'SpecializationId' 
;
   if l_nullable = 'N' then 
        EXECUTE IMMEDIATE 'ALTER TABLE "Groups" MODIFY "SpecializationId"  NULL';
 else 
        EXECUTE IMMEDIATE 'ALTER TABLE "Groups" MODIFY "SpecializationId" ';
 end if;
end;
/

ALTER TABLE "Groups" ADD "FieldOfStudyId" NUMBER(10) DEFAULT 0 NOT NULL
/

CREATE INDEX "IX_Groups_FieldOfStudyId" ON "Groups" ("FieldOfStudyId")
/

ALTER TABLE "Groups" ADD CONSTRAINT "FK_Groups_FieldsOfStudy_FieldOfStudyId" FOREIGN KEY ("FieldOfStudyId") REFERENCES "FieldsOfStudy" ("Id")
/

ALTER TABLE "Groups" ADD CONSTRAINT "FK_Groups_Specializations_SpecializationId" FOREIGN KEY ("SpecializationId") REFERENCES "Specializations" ("Id") ON DELETE SET NULL
/

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES (N'20260501162704_SpecialisationStructureChange', N'10.0.7')
/

ALTER TABLE "Specializations" DROP CONSTRAINT "FK_Specializations_FieldsOfStudy_FieldOfStudyId"
/

DROP INDEX "IX_Specializations_FieldOfStudyId"
/

ALTER TABLE "Specializations" DROP COLUMN "FieldOfStudyId"
/

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES (N'20260501174315_RemoveFieldOfStudyFromSpecialization', N'10.0.7')
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"Logs" (
    "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "TableName" NVARCHAR2(2000) NOT NULL,
    "Operation" NVARCHAR2(2000) NOT NULL,
    "OldValue" NVARCHAR2(2000) NOT NULL,
    "NewValue" NVARCHAR2(2000) NOT NULL,
    "UserChanged" NVARCHAR2(2000) NOT NULL,
    "ChangedAt" TIMESTAMP(7) NOT NULL,
    CONSTRAINT "PK_Logs" PRIMARY KEY ("Id")
)';
END;
/

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES (N'20260505101937_LogTableInit', N'10.0.7')
/

