-- =============================================================================
-- SKRYPT TWORZĄCY STRUKTURĘ BAZY DANYCH (FINALNA WERSJA)
-- =============================================================================

-- 1. Tabele podstawowe (Słowniki i encje niezależne)
-- -----------------------------------------------------------------------------

CREATE TABLE "AcademicYears" (
                                 "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                                 "Name" NVARCHAR2(20) NOT NULL,
                                 "StartDate" TIMESTAMP(7) NOT NULL,
                                 "EndDate" TIMESTAMP(7) NOT NULL
);
/

CREATE TABLE "Faculties" (
                             "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                             "Name" NVARCHAR2(100) NOT NULL,
                             "Abbreviation" NVARCHAR2(10) NOT NULL
);
/

CREATE TABLE "Buildings" (
                             "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                             "Name" NVARCHAR2(100) NOT NULL,
                             "Address" NVARCHAR2(200) NOT NULL,
                             "FacultyId" NUMBER(10) NOT NULL,
                             CONSTRAINT "FK_Buildings_Faculties_FacultyId" FOREIGN KEY ("FacultyId") REFERENCES "Faculties" ("Id") ON DELETE CASCADE
);
/

CREATE TABLE "Permissions" (
                               "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                               "PermissionCode" NVARCHAR2(100) NOT NULL,
                               "Description" NVARCHAR2(2000) NOT NULL
);
/

CREATE TABLE "Roles" (
                         "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                         "Name" NVARCHAR2(50) NOT NULL
);
/

CREATE TABLE "Subjects" (
                            "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                            "Name" NVARCHAR2(200) NOT NULL,
                            "Abbreviation" NVARCHAR2(20) NOT NULL,
                            "Code" NVARCHAR2(50) NOT NULL
);
/

CREATE TABLE "Specializations" (
                                   "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                                   "Name" NVARCHAR2(100) NOT NULL
);
/

CREATE TABLE "Logs" (
                        "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                        "TableName" NVARCHAR2(100) NOT NULL,
                        "Operation" NVARCHAR2(10) NOT NULL,
                        "OldValue" CLOB,
                        "NewValue" CLOB,
                        "UserChanged" NVARCHAR2(100) NOT NULL,
                        "ChangedAt" TIMESTAMP(7) DEFAULT CURRENT_TIMESTAMP NOT NULL
);
/

-- 2. Tabele z relacjami (Klucze obce)
-- -----------------------------------------------------------------------------

CREATE TABLE "Semesters" (
                             "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                             "AcademicYearId" NUMBER(10) NOT NULL,
                             "Name" NVARCHAR2(20) NOT NULL,
                             "StartDate" TIMESTAMP(7) NOT NULL,
                             "EndDate" TIMESTAMP(7) NOT NULL,
                             CONSTRAINT "FK_Semesters_AcademicYears_AcademicYearId" FOREIGN KEY ("AcademicYearId") REFERENCES "AcademicYears" ("Id") ON DELETE CASCADE
);
/

CREATE TABLE "Rooms" (
                         "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                         "BuildingId" NUMBER(10) NOT NULL,
                         "Number" NVARCHAR2(20) NOT NULL,
                         "Capacity" NUMBER(10),
                         "Type" NVARCHAR2(50) NOT NULL,
                         CONSTRAINT "FK_Rooms_Buildings_BuildingId" FOREIGN KEY ("BuildingId") REFERENCES "Buildings" ("Id") ON DELETE CASCADE
);
/

CREATE TABLE "FieldsOfStudy" (
                                 "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                                 "FacultyId" NUMBER(10) NOT NULL,
                                 "Name" NVARCHAR2(100) NOT NULL,
                                 "Degree" NVARCHAR2(50) NOT NULL,
                                 "Mode" NVARCHAR2(50) NOT NULL,
                                 CONSTRAINT "FK_FieldsOfStudy_Faculties_FacultyId" FOREIGN KEY ("FacultyId") REFERENCES "Faculties" ("Id") ON DELETE CASCADE
);
/

CREATE TABLE "Teachers" (
                            "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                            "AcademicTitle" NVARCHAR2(50) NOT NULL,
                            "FirstName" NVARCHAR2(100) NOT NULL,
                            "LastName" NVARCHAR2(100) NOT NULL,
                            "Email" NVARCHAR2(100)
);
/

CREATE TABLE "Students" (
                            "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                            "StudentID" NVARCHAR2(20) NOT NULL,
                            "FirstName" NVARCHAR2(100) NOT NULL,
                            "LastName" NVARCHAR2(100) NOT NULL
);
/

CREATE TABLE "Groups" (
                          "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                          "SemesterId" NUMBER(10) NOT NULL,
                          "FieldOfStudyId" NUMBER(10) NOT NULL,
                          "SpecializationId" NUMBER(10),
                          "Name" NVARCHAR2(50) NOT NULL,
                          "ClassType" NUMBER(10) NOT NULL,
                          CONSTRAINT "FK_Groups_Semesters_SemesterId" FOREIGN KEY ("SemesterId") REFERENCES "Semesters" ("Id") ON DELETE CASCADE,
                          CONSTRAINT "FK_Groups_FieldsOfStudy_FieldOfStudyId" FOREIGN KEY ("FieldOfStudyId") REFERENCES "FieldsOfStudy" ("Id") ON DELETE CASCADE,
                          CONSTRAINT "FK_Groups_Specializations_SpecializationId" FOREIGN KEY ("SpecializationId") REFERENCES "Specializations" ("Id") ON DELETE SET NULL
);
/

CREATE TABLE "Users" (
                         "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                         "Username" NVARCHAR2(50) NOT NULL,
                         "PasswordHash" NVARCHAR2(255) NOT NULL,
                         "Email" NVARCHAR2(100) NOT NULL,
                         "RoleId" NUMBER(10) NOT NULL,
                         "StudentId" NUMBER(10),
                         "TeacherId" NUMBER(10),
                         "IsActive" NUMBER(1) NOT NULL, -- Oracle nie ma typu BOOLEAN w tabelach
                         "LastLogin" TIMESTAMP(7),
                         CONSTRAINT "FK_Users_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE,
                         CONSTRAINT "FK_Users_Students_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Students" ("Id") ON DELETE SET NULL,
                         CONSTRAINT "FK_Users_Teachers_TeacherId" FOREIGN KEY ("TeacherId") REFERENCES "Teachers" ("Id") ON DELETE SET NULL
);
/

-- 3. Tabele asocjacyjne (Wiele-do-wielu) i operacyjne
-- -----------------------------------------------------------------------------

CREATE TABLE "RolePermissions" (
                                   "RoleId" NUMBER(10) NOT NULL,
                                   "PermissionId" NUMBER(10) NOT NULL,
                                   CONSTRAINT "PK_RolePermissions" PRIMARY KEY ("RoleId", "PermissionId"),
                                   CONSTRAINT "FK_RolePermissions_Permissions_PermissionId" FOREIGN KEY ("PermissionId") REFERENCES "Permissions" ("Id") ON DELETE CASCADE,
                                   CONSTRAINT "FK_RolePermissions_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
);
/

CREATE TABLE "StudentGroups" (
                                 "StudentId" NUMBER(10) NOT NULL,
                                 "GroupId" NUMBER(10) NOT NULL,
                                 CONSTRAINT "PK_StudentGroups" PRIMARY KEY ("StudentId", "GroupId"),
                                 CONSTRAINT "FK_StudentGroups_Groups_GroupId" FOREIGN KEY ("GroupId") REFERENCES "Groups" ("Id") ON DELETE CASCADE,
                                 CONSTRAINT "FK_StudentGroups_Students_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Students" ("Id") ON DELETE CASCADE
);
/

CREATE TABLE "Timetables" (
                              "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                              "SubjectId" NUMBER(10) NOT NULL,
                              "TeacherId" NUMBER(10) NOT NULL,
                              "RoomId" NUMBER(10) NOT NULL,
                              "GroupId" NUMBER(10) NOT NULL,
                              "DayOfWeek" NUMBER(10) NOT NULL,
                              "StartTime" INTERVAL DAY(8) TO SECOND(7) NOT NULL,
                              "EndTime" INTERVAL DAY(8) TO SECOND(7) NOT NULL,
                              "WeekCycle" NUMBER(10) NOT NULL,
                              "ClassType" NUMBER(10) NOT NULL,
                              CONSTRAINT "FK_Timetables_Groups_GroupId" FOREIGN KEY ("GroupId") REFERENCES "Groups" ("Id") ON DELETE CASCADE,
                              CONSTRAINT "FK_Timetables_Rooms_RoomId" FOREIGN KEY ("RoomId") REFERENCES "Rooms" ("Id") ON DELETE CASCADE,
                              CONSTRAINT "FK_Timetables_Subjects_SubjectId" FOREIGN KEY ("SubjectId") REFERENCES "Subjects" ("Id") ON DELETE CASCADE,
                              CONSTRAINT "FK_Timetables_Teachers_TeacherId" FOREIGN KEY ("TeacherId") REFERENCES "Teachers" ("Id") ON DELETE CASCADE
);
/

CREATE TABLE "ScheduleChanges" (
                                   "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                                   "TimetableId" NUMBER(10) NOT NULL,
                                   "ChangeDate" TIMESTAMP(7) NOT NULL,
                                   "ChangeType" NVARCHAR2(50) NOT NULL,
                                   "NewRoomId" NUMBER(10),
                                   "NewTeacherId" NUMBER(10),
                                   "NewStartTime" INTERVAL DAY(8) TO SECOND(7),
                                   "NewEndTime" INTERVAL DAY(8) TO SECOND(7),
                                   CONSTRAINT "FK_ScheduleChanges_Rooms_NewRoomId" FOREIGN KEY ("NewRoomId") REFERENCES "Rooms" ("Id") ON DELETE SET NULL,
                                   CONSTRAINT "FK_ScheduleChanges_Teachers_NewTeacherId" FOREIGN KEY ("NewTeacherId") REFERENCES "Teachers" ("Id") ON DELETE SET NULL,
                                   CONSTRAINT "FK_ScheduleChanges_Timetables_TimetableId" FOREIGN KEY ("TimetableId") REFERENCES "Timetables" ("Id") ON DELETE CASCADE
);
/

-- 4. Indeksy dla wydajności
-- -----------------------------------------------------------------------------

CREATE INDEX "IX_Buildings_FacultyId" ON "Buildings" ("FacultyId");
CREATE INDEX "IX_Rooms_BuildingId" ON "Rooms" ("BuildingId");
CREATE INDEX "IX_FieldsOfStudy_FacultyId" ON "FieldsOfStudy" ("FacultyId");
CREATE INDEX "IX_Groups_FieldOfStudyId" ON "Groups" ("FieldOfStudyId");
CREATE INDEX "IX_Groups_SpecializationId" ON "Groups" ("SpecializationId");
CREATE INDEX "IX_Timetables_GroupId" ON "Timetables" ("GroupId");
CREATE INDEX "IX_Timetables_RoomId" ON "Timetables" ("RoomId");
/