<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
      <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.7" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.7">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.7" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.7" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.7">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.2" />
      <PackageReference Include="NuGet.Packaging" Version="7.6.0" />
      <PackageReference Include="NuGet.Protocol" Version="7.6.0" />
      <PackageReference Include="Oracle.EntityFrameworkCore" Version="10.23.26200" />
      <PackageReference Include="QuestPDF" Version="2026.5.0" />
      <PackageReference Include="Scrutor" Version="7.0.0" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Migrations\20260505195941_RoomChanges.Designer.cs">
        <DependentUpon>20260501160153_RoomChanges.cs</DependentUpon>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="Views\Teachers\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Buildings\Create.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Buildings\Delete.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Buildings\Details.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Buildings\Edit.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Buildings\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Timetables\Create.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Timetables\Delete.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Timetables\Details.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Timetables\Edit.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Timetables\Index.cshtml" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="Views\Home\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Home\Privacy.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Scraper\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Teachers\Index.cshtml" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="DTOs\Group\" />
    </ItemGroup>

</Project>
